In [0]:
import torch

In [0]:
def sigmoid(x):
  return 1/(1+torch.exp(-x))

In [0]:
torch.manual_seed(7)

features = torch.randn((1,5))
weights = torch.randn_like(features)

bias = torch.randn((1,1))

In [9]:
y = sigmoid(torch.sum(features*weights) + bias)
y

tensor([[0.1595]])

In [18]:
weights = weights.view((5,1))
#weights.shape

y = sigmoid(torch.mm(features,weights) + bias)
y

tensor([[0.1595]])

In [0]:

### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [23]:
y1 = sigmoid(torch.matmul(features, W1) + B1)
y1

tensor([[0.6813, 0.4355]])

In [24]:
y2 = sigmoid(torch.matmul(y1, W2) + B2)
y2

tensor([[0.3171]])

In [25]:
# Torch to numpy to Torch
import numpy as np
a = np.random.rand(4,3)
a

array([[0.59546705, 0.57500768, 0.75819577],
       [0.43928203, 0.59761369, 0.71631305],
       [0.4310064 , 0.96475131, 0.19697307],
       [0.36615015, 0.71626492, 0.9235685 ]])

In [29]:
b= torch.from_numpy(a)
b

tensor([[0.5955, 0.5750, 0.7582],
        [0.4393, 0.5976, 0.7163],
        [0.4310, 0.9648, 0.1970],
        [0.3662, 0.7163, 0.9236]], dtype=torch.float64)

In [33]:
b.numpy()

array([[0.59546705, 0.57500768, 0.75819577],
       [0.43928203, 0.59761369, 0.71631305],
       [0.4310064 , 0.96475131, 0.19697307],
       [0.36615015, 0.71626492, 0.9235685 ]])

In [31]:
b

tensor([[0.5955, 0.5750, 0.7582],
        [0.4393, 0.5976, 0.7163],
        [0.4310, 0.9648, 0.1970],
        [0.3662, 0.7163, 0.9236]], dtype=torch.float64)

In [34]:
a

array([[0.59546705, 0.57500768, 0.75819577],
       [0.43928203, 0.59761369, 0.71631305],
       [0.4310064 , 0.96475131, 0.19697307],
       [0.36615015, 0.71626492, 0.9235685 ]])

In [35]:
b.mul_(2)

tensor([[1.1909, 1.1500, 1.5164],
        [0.8786, 1.1952, 1.4326],
        [0.8620, 1.9295, 0.3939],
        [0.7323, 1.4325, 1.8471]], dtype=torch.float64)

In [36]:
a

array([[1.1909341 , 1.15001536, 1.51639154],
       [0.87856405, 1.19522738, 1.43262611],
       [0.8620128 , 1.92950262, 0.39394613],
       [0.7323003 , 1.43252985, 1.84713701]])